genome:
  id: 26045
  # The traits used in this genome
  traits: 
    - {id: 1,  params: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 2,  params: [0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 3,  params: [0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 4,  params: [0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 5,  params: [0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 6,  params: [0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 7,  params: [0.7, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 8,  params: [0.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 9,  params: [0.9, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 10, params: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 11, params: [1.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 12, params: [1.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 13, params: [1.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 14, params: [1.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
  #   - {id: 15, params: [1.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}

  # The neuron nodes for this genome
  nodes:
    # The input nodes - sensors
    - {id: 1,  trait_id: 0, type: INPT, activation: NullActivation}
    - {id: 2,  trait_id: 0, type: INPT, activation: NullActivation}
    - {id: 3,  trait_id: 0, type: INPT, activation: NullActivation}
    - {id: 4,  trait_id: 0, type: INPT, activation: NullActivation}
    - {id: 5,  trait_id: 0, type: INPT, activation: NullActivation}
    - {id: 6,  trait_id: 0, type: INPT, activation: NullActivation}
    - {id: 7,  trait_id: 0, type: INPT, activation: NullActivation}
    - {id: 8,  trait_id: 0, type: INPT, activation: NullActivation}
    - {id: 9,  trait_id: 0, type: INPT, activation: NullActivation}
    - {id: 10,  trait_id: 0, type: INPT, activation: NullActivation}
    - {id: 11,  trait_id: 0, type: INPT, activation: NullActivation}
    - {id: 12,  trait_id: 0, type: INPT, activation: NullActivation}
    # The output nodes - actuators
    - {id: 1001,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1002,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1003,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1004,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1005,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1006,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1007,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1008,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1009,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1010,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1011,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1012,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1013,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1014,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1015,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1016,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1017,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1018,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1019,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1020,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1021,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1022,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1023,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1024,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1025,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1026,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1027,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1028,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1029,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1030,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1031,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1032,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1033,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1034,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1035,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1036,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1037,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1038,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1039,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1040,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1041,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1042,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1043,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1044,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1045,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1046,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1047,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1048,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1049,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1050,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1051,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1052,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1053,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1054,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1055,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1056,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1057,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1058,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1059,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1060,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1061,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1062,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1063,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1064,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1065,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1066,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1067,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1068,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1069,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1070,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1071,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1072,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1073,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1074,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1075,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1076,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1077,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1078,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1079,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1080,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1081,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1082,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1083,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1084,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1085,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1086,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1087,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1088,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1089,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1090,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1091,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1092,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1093,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1094,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1095,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1096,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1097,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1098,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1099,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1100,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1101,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1102,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1103,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1104,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1105,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1106,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1107,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1108,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1109,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1110,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1111,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1112,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1113,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1114,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1115,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1116,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1117,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1118,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1119,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1120,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1121,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1122,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1123,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1124,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1125,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1126,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1127,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}
    - {id: 1128,  trait_id: 0, type: OUTP, activation: SigmoidPlainActivation}

    # The bias nodes
    - {id: 2001,  trait_id: 0, type: BIAS, activation: NullActivation}

    # # The first module input/output nodes
    # - {id: 16,  trait_id: 0, type: HIDN, activation: LinearActivation}
    # - {id: 17,  trait_id: 0, type: HIDN, activation: LinearActivation}
    # - {id: 18, trait_id: 0, type: HIDN, activation: NullActivation}
    # # The second module input/output nodes
    # - {id: 19, trait_id: 0, type: HIDN, activation: LinearActivation}
    # - {id: 20, trait_id: 0, type: HIDN, activation: LinearActivation}
    # - {id: 21, trait_id: 0, type: HIDN, activation: NullActivation}
    # The hidden node
    # - {id: 22, trait_id: 0, type: HIDN, activation: SignActivation}

  # # The modules (activators with multiple inputs/outputs). Allows to route outputs of group of neurons within genome and apply specific activation function en route.
  # modules:
  #   -
  #     id: 23
  #     trait_id: 0
  #     activation: MultiplyModuleActivation
  #     innov_num: 16
  #     mut_num: 0.5
  #     enabled: true
  #     inputs:
  #       - {id: 16,  order: 0}
  #       - {id: 17,  order: 1}
  #     outputs:
  #       - {id: 18, order: 0}
  #   -
  #     id: 24
  #     trait_id: 0
  #     activation: MultiplyModuleActivation
  #     innov_num: 17
  #     mut_num: 1.5
  #     enabled: true
  #     inputs:
  #       - {id: 19, order: 0}
  #       - {id: 20, order: 1}
  #     outputs:
  #       - {id: 21, order: 0}

  # # The genes - connection between neuron nodes within this genome
  genes: 
    - {src_id: 2001,  tgt_id: 1001,  weight: 0.0, trait_id: 1, innov_num: 1,  mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 2,  tgt_id: 6,  weight: 0.0, trait_id: 2, innov_num: 2,  mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 5,  tgt_id: 6,  weight: 0.0, trait_id: 3, innov_num: 3,  mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 6,  tgt_id: 14, weight: 1.0, trait_id: 4, innov_num: 4,  mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 14, tgt_id: 8,  weight: 1.0, trait_id: 4, innov_num: 5,  mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 2,  tgt_id: 9,  weight: 0.0, trait_id: 3, innov_num: 6,  mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 10, tgt_id: 6,  weight: 0.0, trait_id: 3, innov_num: 7,  mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 4,  tgt_id: 12, weight: 0.0, trait_id: 3, innov_num: 8,  mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 14, tgt_id: 11, weight: 1.0, trait_id: 3, innov_num: 9,  mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 13, tgt_id: 6,  weight: 0.0, trait_id: 3, innov_num: 10, mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 1,  tgt_id: 7,  weight: 0.0, trait_id: 3, innov_num: 11, mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 3,  tgt_id: 7,  weight: 0.0, trait_id: 3, innov_num: 12, mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 5,  tgt_id: 7,  weight: 0.0, trait_id: 3, innov_num: 13, mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 10, tgt_id: 7,  weight: 0.0, trait_id: 3, innov_num: 14, mut_num: 0, recurrent: false, enabled: true}
  #   - {src_id: 13, tgt_id: 7,  weight: 0.0, trait_id: 3, innov_num: 15, mut_num: 0, recurrent: false, enabled: true}